global using Domain.Abstractions.Aggregates;
global using Domain.Abstractions.Commands;
global using Domain.Abstractions.Queries;
global using Domain.Abstractions.Repositories;
global using Domain.Exceptions;
global using MediatR;
global using StrongTypedId;
global using Domain.Todos.Repositories;
global using Domain.Todos.Commands.Abstractions;
